# Generated by Django 2.2.10 on 2021-05-11 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='estimate_inputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(default=datetime.date(2021, 5, 12))),
                ('construnction_start_date', models.DateField()),
                ('target_price', models.FloatField(blank=True)),
                ('carrier', models.CharField(max_length=255)),
                ('landlord', models.CharField(max_length=255)),
                ('turf_vendor', models.CharField(max_length=255)),
                ('site_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_tower_work', models.CharField(choices=[('yes', 'YES'), ('no', 'No')], max_length=255)),
                ('towers_personnel', models.IntegerField()),
                ('expected_tower_working_days', models.IntegerField()),
                ('expected_tower_working_hours', models.IntegerField()),
                ('tower_trucks', models.IntegerField()),
                ('tower_trailers', models.IntegerField()),
                ('is_civil_work', models.CharField(choices=[('yes', 'YES'), ('no', 'No')], max_length=255)),
                ('civil_personnel', models.IntegerField()),
                ('expected_civil_working_days', models.IntegerField()),
                ('expected_civil_working_hours', models.IntegerField()),
                ('civil_trucks', models.IntegerField()),
                ('civil_trailers', models.IntegerField()),
                ('is_box_trucks_used', models.CharField(choices=[('yes', 'YES'), ('no', 'No')], max_length=255)),
                ('box_trcuk_utilization', models.CharField(max_length=255)),
                ('is_perdiem', models.CharField(choices=[('yes', 'YES'), ('no', 'No')], max_length=255)),
                ('expected_perdiem_working_days', models.IntegerField()),
                ('days_on_perdiem', models.IntegerField()),
                ('distance_to_site', models.IntegerField()),
            ],
        ),
    ]
