# Generated by Django 2.2.10 on 2021-05-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_estimate_inputs'),
    ]

    operations = [
        migrations.CreateModel(
            name='base_values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_number', models.CharField(max_length=255)),
                ('truck_per_mile', models.FloatField()),
                ('trailer_per_day', models.FloatField()),
                ('fuel_rate', models.FloatField()),
                ('avg_work_truck_mpg', models.IntegerField()),
                ('avg_tower_tech', models.FloatField()),
                ('avg_civil_tech', models.FloatField()),
                ('loaging_rate', models.FloatField()),
                ('m_i_rate', models.FloatField()),
                ('warehouse_log_rate', models.IntegerField()),
                ('sg_a_overhead_rate', models.IntegerField()),
                ('desired_margin', models.IntegerField()),
            ],
        ),
    ]
