# Generated by Django 2.2.10 on 2021-05-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_base_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_values',
            name='site_number',
            field=models.CharField(max_length=255, verbose_name='Site number'),
        ),
    ]
