# Generated by Django 2.2.10 on 2021-05-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20210512_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_values',
            name='avg_civil_tech',
            field=models.FloatField(verbose_name='Average Civil Tech Hourly Wage'),
        ),
        migrations.AlterField(
            model_name='base_values',
            name='avg_tower_tech',
            field=models.FloatField(verbose_name='Average Tower Tech Hourly Wage'),
        ),
        migrations.AlterField(
            model_name='base_values',
            name='avg_work_truck_mpg',
            field=models.IntegerField(verbose_name='Average Work Truck MPG'),
        ),
        migrations.AlterField(
            model_name='base_values',
            name='desired_margin',
            field=models.IntegerField(verbose_name='Desired Margin'),
        ),
        migrations.AlterField(
            model_name='base_values',
            name='fuel_rate',
            field=models.FloatField(verbose_name='Fuel Rate'),
        ),
        migrations.AlterField(
            model_name='base_values',
            name='loaging_rate',
            field=models.FloatField(verbose_name='Lodging Rate'),
        ),
        migrations.AlterField(
            model_name='base_values',
            name='m_i_rate',
            field=models.FloatField(verbose_name='M&I Rate'),
        ),
        migrations.AlterField(
            model_name='base_values',
            name='sg_a_overhead_rate',
            field=models.IntegerField(verbose_name='SG&A Overhead Rate (% of Expenses)'),
        ),
        migrations.AlterField(
            model_name='base_values',
            name='trailer_per_day',
            field=models.FloatField(verbose_name='Trailer Per Day'),
        ),
        migrations.AlterField(
            model_name='base_values',
            name='truck_per_mile',
            field=models.FloatField(verbose_name='Truck Per Mile'),
        ),
    ]
