# Generated by Django 2.2.10 on 2021-05-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20210512_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
